### PR TITLE
Add 2019 Wristbands

### PR DESCRIPTION
**Pull request by raccube**

### CODE REVIEW

**Comment by Tyler-Ward** [comment]
Looking good, I think we are almost there with these.

* Is the logo going to be in the crimping area as it looks quite far left in the render. 
* looking at their website it looks like they have a limited pallet of thread colors which there isn't a good dark red in, we could go for printed fabric wristbands which would avoid this issue or see the other background uploaded in the issue.
* Do we want to have caldera on both ends of the band.
* the logo size to text name differs from the style guide, however if we do use the proscribed sizing we would either have small text or need to crop the round part of the logo. what are people thoughts on this.

**Comment by RealOrangeOne** [comment]
This looks great! Much more interesting than previous years! 

Printed fabric would lead to it looking much nicer, but I don't know how durable the design would be. At least with it stitched in it's not going to fade at all.

I suspect the logo _is_ too far over to the left, if we move it closer then that should be enough. We can move the text to the right a bit if needs be anyway.

Looks like there's also a transparent area around the SVG (although that might just be GitHub rendering it)

**Comment by Tyler-Ward** [comment]
Can the .png background be force pushed opt of the repo when you add the svg background (its quite large and I can see the promotional material repo getting very large if we leave lots of them in the tree.

**Comment by PeterJCLaw** [comment]
Looking nice, thanks for doing this.

Can we check ahead of time whether the place who are going to be making these have the fonts in question? If there's any doubt then we should convert the text to paths before submission.

I agree that having our name slightly large (even if slightly against the usual guidelines) is probably the right call here, but cc @jimmythompson in case he feels strongly.

I agree that having a bit larger space for where the crimp will go is probably a good idea if possible.

I _do_ think we should have the game name on both ends.

**Comment by raccube** [comment]
@PeterJCLaw I already converted them to paths.

**Review by Tyler-Ward — CHANGES_REQUESTED** [review]
we should force push to remove the background png and svg with integrated png to avoid this repo getting too large. 

Also it might just be me but the caldera on the right seems a lot further in than the one on the left, not sure if that is intentional.

**Comment by Tyler-Ward** [comment]
Other than the bits above this is looking great, once we get those sorted we can get these ordered, would ideally like to order today if possible now that the budget is unblocked.

**Comment by raccube** [comment]
I've moved the right one slightly so that they're both 3cm in.

Reference screenshot with guides: 
image

**Comment by raccube** [comment]
Ok so apparently force-pushing closes PRs

**Pull request closed without merging**
