### PR TITLE
Added tablecloth designs

### PR DESCRIPTION
**Pull request by Tyler-Ward**
Tablecloth designs for named locations and general use.

Plain
location

### CODE REVIEW

**Comment by antoinepetty** [comment]
The tall letters look out of place here imo - maybe try with Open Sans Condensed? https://srobo.github.io/style/

**Comment by Tyler-Ward** [comment]
Here is a version in opensans condensed
location

**Review by antoinepetty — APPROVED** [review]

**Comment by antoinepetty** [comment]
Is that using the old blue? Should we be using the new blue? (I'm just being pedantic now)

**Comment by Tyler-Ward** [comment]
The blue is just for visualizing the logo as white on transparent isnt visible on github.

**Comment by RealOrangeOne** [comment]
> The blue is just for visualizing the logo as white on transparent isnt visible on github.

What colour will the background be? I think we should either match the background colour, or remove it. Transparent images are an issue everywhere, but it's still fine to review. https://github.com/srobo/comp-floorplans/pull/3 worked just fine

**Comment by Tyler-Ward** [comment]
The background will be the tablecloth color. There is no background on the committed SVGs only on the preview PNGs in the discussion

**Comment by RealOrangeOne** [comment]
> There is no background on the committed SVGs only on the preview PNGs in the discussion

ah yes :man_facepalming:

**Review by trickeydan — APPROVED** [review]

**Comment by PeterJCLaw** [comment]
Not sure if it's just a function of the previews, but the location text here looks _way_ too close to the logo. https://studentrobotics.org/style/ suggests a 5% padding, yet the design here is fully overlapping the space.

**Comment by Tyler-Ward** [comment]
We can go for a larger print area to give some more spacing. opinions on the one below?

location

**Comment by PeterJCLaw** [comment]
yeah, that looks much better to me, thanks

(as a small suggestion on the fonts, I'd be tempted to try "Helpdesk" being in caps in Oswald - per the Hero text styling, but I'm less worried about this aspect)

**Comment by Tyler-Ward** [comment]
preview of location name back to Oswald and now in caps.

location

**Pull request merged**
