### PR TITLE
Add SR2022 Banner and move SR2019's

### PR DESCRIPTION
**Pull request by antoinepetty**
First pass at a banner. Not sure about alignment or positioning yet

### CODE REVIEW

**Comment by antoinepetty** [comment]
Related to https://github.com/srobo/marketing-team-minutes/issues/38

**Comment by antoinepetty** [comment]
Latest version:
banner

**Comment by antoinepetty** [comment]
We may need to add IET, waiting for confirmation on what branding they require

**Comment by RealOrangeOne** [comment]
The version in the repo doesn't seem to have the itdev logo, is that intentional?

**Comment by antoinepetty** [comment]
It should be included but it's a png instead of svg. Not sure if it's not been included for some reason?

**Comment by RealOrangeOne** [comment]
Ah, looks like it is actually there, it just takes a while to pop in, which is quite strange!

**Comment by antoinepetty** [comment]
Current state:
banner

**Comment by antoinepetty** [comment]
banner

**Comment by Scarzy** [comment]
IET require reviewing this before it can be used, so this is currently blocked on their feedback

**Comment by sedders123** [comment]
IET and IMechE have approved the design

**Review by sedders123 — APPROVED** [review]

**Pull request merged**
