### PR TITLE
Added Shirts

### PR DESCRIPTION
**Pull request by TomWheal**
ShirtMockupFront

ShirtMockupBack1

### CODE REVIEW

**Review by Tyler-Ward — CHANGES_REQUESTED** [review]
Design looks good so we can order the shirts, lets remove the PSD file from the repo (force push) and split the SVG up to make the files a bit easier to use in the future.

**Comment by TomWheal** [comment]
Done, shall I add the Mockup .psd and mockups to a release maybe so that they are on the git?

**Comment by Tyler-Ward** [comment]
That sounds like a good idea to me

**Comment by TomWheal** [comment]
Not sure I can do that here so I've added it to my fork https://github.com/TomWheal/promotional-material/releases/tag/v1.0

**Review by RealOrangeOne — APPROVED** [review]

**Comment by RealOrangeOne** [comment]
There was much discussion and agreement in person around the shirts being good. We can consider this fine now and merge it

**Pull request merged**
